---
title: "sydneyschmitter_A1"
author: "Sydney Schmitter"
date: "9/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# I first downloaded gas and electricity data from PGE that spanned from Q1 of 2017 to Q2 of 2021. From here, I wanted to read all of the data I downloaded, which I accomplished with a for loop.
# In this for loop, I had the for loop read from Q1 of 2017 to Q4 of 2020 for PGE electricity data. Once I read these files, I bound them in pge_20_elec.
library(tidyverse)
years <- 2017:2020
quarters <- 1:4
types <-c("Electric")
  
pge_20_elec <- NULL

for (type in types){
for (year in years){
  for (quarter in quarters) {
  
    filename <- 
      paste0(
        "PGE_",
        year,
        "_Q",
        quarter,
        "_",
        type,
        "UsageByZip.csv"
      )

    print(filename)
  
    temp <- read_csv(filename)
    
    pge_20_elec <- rbind(pge_20_elec, temp)
    
    }
}
}
```

```{r}
# In this for loop, I had the for loop read from Q1 of 2017 to Q4 of 2020 for PGE gas data, like I did above. Once I read these files, I bound them in pge_20_gas.
library(tidyverse)
library(tidyverse)
years <- 2017:2020
quarters <- 1:4
types <-c("Gas")
  
pge_20_gas <- NULL

for (type in types){
for (year in years){
  for (quarter in quarters) {
  
    filename <- 
      paste0(
        "PGE_",
        year,
        "_Q",
        quarter,
        "_",
        type,
        "UsageByZip.csv"
      )

    print(filename)
  
    temp <- read_csv(filename)
    
    pge_20_gas <- rbind(pge_20_gas,temp)
    
    }
}
}
```

```{r}
# The reason why I could only read from 2017 to 2020 in my previous 2 for loops is that only Q1 and Q2 data for 2021 gas and electricity data is currently available. 
# In this for loop, I had the for loop read from Q1 of 2021 to Q2 of 2021 for PGE electricity data. Once I read these files, I bound them in pge_21_elec.
library(tidyverse)
years <- 2021:2021
quarters <- 1:2
types <-c("Electric")

pge_2021_elec <- NULL
 
for (type in types){
for (year in years){
  for (quarter in quarters) {
  
    filename <- 
      paste0(
        "PGE_",
        year,
        "_Q",
        quarter,
        "_",
        type,
        "UsageByZip.csv"
      )

    print(filename)
  
    temp <- read_csv(filename)
    
    pge_2021_elec <- rbind(pge_2021_elec, temp)
    }
}
}
```

```{r}
# The reason why I could only read from 2017 to 2020 in my previous 2 for loops is that only Q1 and Q2 data for 2021 gas and electricity data is currently available. 
# In this for loop, I had the for loop read from Q1 of 2021 to Q2 of 2021 for PGE gas data. Once I read these files, I bound them in pge_21_gas.
library(tidyverse)
years <- 2021:2021
quarters <- 1:2
types <-c("Gas")

pge_2021_gas <- NULL

for (type in types){
for (year in years){
  for (quarter in quarters) {
  
    filename <- 
      paste0(
        "PGE_",
        year,
        "_Q",
        quarter,
        "_",
        type,
        "UsageByZip.csv"
      )

    print(filename)
  
    temp <- read_csv(filename)
    
    pge_2021_gas <- rbind(pge_2021_gas, temp)
    }
}
}
```

```{r}
#Combine 2017-2021 data to create one combined data set each for PGE gas and electric data
pge_combined_elec <- rbind(pge_20_elec,pge_2021_elec)
pge_combined_gas <- rbind(pge_20_gas,pge_2021_gas)

nrow(pge_combined_elec)
unique(pge_combined_elec$CUSTOMERCLASS)

nrow(pge_combined_gas)
unique(pge_combined_gas$CUSTOMERCLASS)
```

```{r}
#In my graph, I will only be plotting residential and commercial consumption, so I will alter my .csv files to include only this data. I am looking only for residential and commercial data, so I will filter electric data to include only Elec- Residential and Elec- Commercial. However, gas data is already divided into exclusively residential and commercial data so I do not need to filter gas.

library(tidyverse)
pge_filter_elec <- 
  filter(
    pge_combined_elec,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Elec- Commercial"
      )
  )
```

```{r}
#Now, I need to convert THM and KWH data to KBTUs using a mutation.
pge_electric_kbtu <- mutate (pge_filter_elec, TOTALKBTUs=TOTALKWH*3.412)
pge_gas_kbtu <- mutate (pge_combined_gas, TOTALKBTUs=TOTALTHM*99.976)
```

```{r}
#Now, I can filter the exact data I need for pge electric and gas data.
pge_electric_final <- pge_electric_kbtu %>% select(
    -c(ZIPCODE, COMBINED, TOTALCUSTOMERS,TOTALKWH,AVERAGEKWH))
pge_gas_final <- pge_gas_kbtu %>% select(
    -c(ZIPCODE, COMBINED, TOTALCUSTOMERS,TOTALTHM,AVERAGETHM))

#Now, I am in the correct format to bind both gas and electric data to form one complete data set.
pge_data_raw <-rbind(pge_electric_final, pge_gas_final)
```

```{r}
#I was told that I need to mutate my dates before plotting to make it easier for plotting functions to understand.
pge_data <-
  pge_data_raw %>% 
  mutate(
    DATE = 
      paste(
        YEAR,
        MONTH, 
        "01",
        sep="-"
      ) %>% as.Date()
  )

```

```{r}
#Here, I filter for residential gas and electricty use for my residential data plot.
library(ggplot2)
library(tidyverse)

pge_residential_data <-
  filter(
    pge_data,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Residential",
        "Gas- Residential"
      )
  )

#Here, I plot my residential data plot.
pge_chart <-
  pge_residential_data %>% 
  ggplot() +
  geom_bar(
    aes(
      x = DATE,
      y = TOTALKBTUs,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "Total KBTUs",
    title = "PG&E Territory Monthly Residential Electricity and Gas Usage",
    fill = "Residential Gas and Electricity Usage"
  )
pge_chart
```

```{r}
#Here, I filter for commercial gas and electricty use for my commercial data plot.
pge_commercial_data <-
    filter(
    pge_data,
    CUSTOMERCLASS %in% 
      c(
        "Elec- Commercial",
        "Gas- Commercial"
      )
  )

#Here, I plot my commercial data plot.
pge_chart <-
  pge_commercial_data %>% 
  ggplot() +
  geom_bar(
    aes(
      x = DATE,
      y = TOTALKBTUs,
      fill = CUSTOMERCLASS
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Month",
    y = "Total KBTUs",
    title = "PG&E Territory Monthly Commercial Electricity and Gas Usage",
    fill = "Commercial Gas and Electricity Usage"
  )
pge_chart
```
```{r}
#Now, I will comment on any observable changes in energy consumption that may be attributable to the COVID-19 pandemic. Upon analyzing the residential data plot, I see increases in residential gas and electricity consumption in the beginning of each year. I assume that this increase in energy consumption is a result of the energy needed to warm residential homes during colder, winter months. Energy consumption decreases in summer and spring months due to a lack of necessity to heat residential homes. In the commercial sector, I note the same cycle of an increase in energy consumption in the winter and a decrease in energy consumption in spring and summer months. Between 2019 and 2020 for residential energy use, I noticed that there was a general slight increase in gas and electricity usage across the entire year of 2020, which could be attributed to the COVID-19 pandemic as people spent more time in their homes. Between 2019 and 2020 for commercial energy use, I noticed that there was a slight decrease in commercial energy use. I would also attribute this decrease to the COVID-19 pandemic as the commercial sector was at times shut down completely during shutdowns and social distancing measures were implemented in the workplace.
```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
