---
title: "sydneyschmitter_a6"
author: "Sydney Schmitter"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(censusapi)
library(sf)
library(mapview)
library(tigris)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```

```{r}
# pums_2019_1yr <- getCensus(
#   name = "acs/acs1/pums",
#   vintage = 2019,
#   region = "public use microdata area:*", 
#   regionin = "state:06",
#   vars = c(
#     "SERIALNO",
#     "SPORDER",
#     "PWGTP",
#     "WGTP",
#     "YBL",
#     "BLD",
#     "TEN",
#     "MV",
#     "HINCP",
#     "AGEP"
#   )
# )

# saveRDS(pums_2019_1yr, "a6_pums.rds")
pums_2019_1yr <- readRDS("a6_pums.rds")
```

```{r}
ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

sf_pums <-
  pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)

sf_pums_clean <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)
  ) %>% 
  filter(YBL %in% 1:3) %>% 
  arrange(AGEP) %>% 
  group_by(SERIALNO) %>% 
  summarize_all(first) %>% 
  mutate(
    leadrisk = ifelse((AGEP %in% 0:6) & (HINCP < 90000), 1, 0 )
  ) %>% 
  mutate(
    BLD = BLD %>% 
      factor(
        levels = sf_pums$BLD %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      )
  ) %>% 
  mutate(
    TEN = TEN %>% 
      factor(
        levels = sf_pums$TEN %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      )
  ) %>% 
  mutate(
    MV = MV %>% 
      factor(
        levels = sf_pums$MV %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      )
  ) %>% 
  mutate(
    PUMA = PUMA %>% 
      factor(
        levels = sf_pums$PUMA %>% 
          unique() %>%
          sort()
      )
    )

logit_model <- glm(
  leadrisk ~ BLD + TEN + MV + PUMA,
  family = quasibinomial(),
  data = sf_pums_clean
)

exp(coef(logit_model))

exp(coef(logit_model))/(exp(coef(logit_model))+1)

summary(logit_model)
# Call:
# glm(formula = leadrisk ~ BLD + TEN + MV + PUMA, family = quasibinomial(), 
#     data = sf_pums_clean)
# 
# Deviance Residuals: 
#     Min       1Q   Median       3Q      Max  
# -0.8317  -0.2217  -0.1364  -0.0700   3.2804  
# 
# Coefficients:
#               Estimate Std. Error t value Pr(>|t|)   
# (Intercept) -2.332e+01  1.103e+04  -0.002  0.99831   
# BLD2         1.766e+01  1.103e+04   0.002  0.99872   
# BLD3         1.723e+01  1.103e+04   0.002  0.99875   
# BLD4         1.675e+01  1.103e+04   0.002  0.99879   
# BLD5         1.652e+01  1.103e+04   0.001  0.99881   
# BLD6         1.663e+01  1.103e+04   0.002  0.99880   
# BLD7         1.896e-01  1.109e+04   0.000  0.99999   
# BLD8         3.098e-01  1.109e+04   0.000  0.99998   
# BLD9         1.693e+01  1.103e+04   0.002  0.99878   
# BLD10        6.194e-01  1.930e+04   0.000  0.99997   
# TEN2        -4.991e-01  5.303e-01  -0.941  0.34671   
# TEN3         1.036e+00  3.637e-01   2.850  0.00442 **
# TEN4         1.404e+00  7.561e-01   1.857  0.06343 . 
# MV2          5.552e-01  7.528e-01   0.737  0.46093   
# MV3          1.029e+00  6.011e-01   1.712  0.08697 . 
# MV4          9.728e-01  6.021e-01   1.616  0.10631   
# MV5          3.247e-01  6.430e-01   0.505  0.61366   
# MV6          6.128e-02  7.086e-01   0.086  0.93109   
# MV7          1.250e-01  6.978e-01   0.179  0.85788   
# PUMA07502    1.098e+00  7.865e-01   1.396  0.16295   
# PUMA07503    4.436e-01  9.189e-01   0.483  0.62929   
# PUMA07504    1.774e+00  7.003e-01   2.533  0.01137 * 
# PUMA07505    9.688e-02  9.051e-01   0.107  0.91477   
# PUMA07506    2.056e+00  7.055e-01   2.914  0.00361 **
# PUMA07507    2.338e+00  7.124e-01   3.282  0.00105 **
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# (Dispersion parameter for quasibinomial family taken to be 0.7976752)
# 
#     Null deviance: 433.92  on 2263  degrees of freedom
# Residual deviance: 368.61  on 2239  degrees of freedom
# AIC: NA
# 
# Number of Fisher Scoring iterations: 19


#Example of predicted likelihood score
sample_predict <- sample_n(sf_pums_clean, 1)

predict(logit_model, sample_predict, type = "response")
#           1 
# 0.003671029 

predictedscore <- predict(logit_model, sf_pums_clean, type = "response")

sf_pums_predicted <- cbind(sf_pums_clean, predictedscore)

sample <- sample(
  c(TRUE, FALSE), 
  nrow(sf_pums_predicted), 
  replace = T, 
)

test <- sf_pums_predicted[!sample, ]

summary_2x2 <-
  sf_pums_predicted %>% 
  mutate(
    leadrisk = ifelse(
      leadrisk == 1, 
      "Lead Risk (Positive)", 
      "No Lead Risk (Negative)"
    )
  ) %>% 
  pull(leadrisk) %>% 
  table(predictedscore >= 0.10)


summary_2x2
  #                       FALSE TRUE
  # Lead Risk (Positive)       37    7
  # No Lead Risk (Negative)  2183   37

#Values that would typically exceed the threshold score of .10 would be households with values of BLD > 2, TEN > 3, and MV > 2.
#Based on threshhold scores, the organization would mail out 44 postcards, and the percentage of postcards that would actually go to low-income households with children is 18.9%.
#The percentage of all at-risk children likely to be reached is 1.9%.
#I might improve my strategy by distributing postcards to elementary schools in neighborhoods where I have identified a higher risk of at-risk children.
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
