---
title: "sydneyschmitter_A2"
author: "Sydney Schmitter"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
#First, I downloaded the packages I needed for this assignment.
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(mapview)
library(leaflet)
library(ggplot2)
```

```{r}
#Next, I knew that I needed to grab decennial census data for both 2020, as well as 2010.
Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

#Here, I grabbed 2020 decennial census data for San Mateo County.
smc_pop_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P1_001N"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P1_001N
  )

dec_vars_2020 <-
  listCensusMetadata(
    name = "2020/dec/pl",
    type = "variables"
  )

#Next, I took San Mateo County data and sorted it into a new dataframe that organized population by race. I placed this code here because I want to demonstrate that I can filter by race. However, I did not attempt to map by race as I had several issues with this assignment.
smc_pop_race_2020 <-
  getCensus(
    name = "dec/pl",
    vintage = 2020,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    ends_with("N"),
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2020 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )

dec_vars_2020 %>% 
  filter(grepl("P1",name)) %>% 
  select(name, label) %>% 
  arrange(name)

#I had an extra category of columns in my dataframe so I eliminated this category with a mutation.
smc_pop_race_2020 <- smc_pop_race_2020 %>% 
  mutate(
    race = case_when(
      category1 == "Population of two or more races:" & is.na(category2) ~ "Two or more races",
      category1 == "Population of two or more races:" ~ "",
      !is.na(category2) ~ category2,
      TRUE ~ ""
    )
  )

smc_pop_race_2020 <- smc_pop_race_2020 %>% 
  filter(race != "") %>% 
  select(block, race, pop = estimate
  )

#I created a shapefile to map the boundaries of San Mateo County
blocks_2020 <- blocks("CA", "San Mateo", year = 2020, progress_bar = F)

#I created a shapefile to map the boundaries of North Fair Oaks
nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

#I created a specific population dataset for North Fair Oaks
nfo_pop_2020 <- smc_pop_2020 %>% 
  left_join(blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(blocks_2020 %>% select(block = GEOID20)) %>% 
  st_as_sf()
```

```{r}
Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

#Like above, I repeated the same exact process for 2010 decennial census data.
smc_pop_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "P001001"
  ) %>% 
  transmute(
    block =
      paste0(state,county,tract,block),
    pop = P001001
  )

dec_vars_2010 <-
  listCensusMetadata(
    name = "2010/dec/pl",
    type = "variables"
  )

smc_pop_race_2010 <-
  getCensus(
    name = "dec/pl",
    vintage = 2010,
    region = "block:*", 
    regionin = "state:06+county:081",
    vars = "group(P1)"
  ) %>% 
  mutate(
    block =
      paste0(state,county,tract,block)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,NAME) & !ends_with(c("NA"))) %>% 
  pivot_longer(
    -block,
    names_to = "name",
    values_to = "estimate"
  ) %>%
  left_join(
    dec_vars_2010 %>% 
      select(name, label)
  ) %>% 
  select(-name) %>% 
  separate(
    label,
    into = c(NA,NA,"category1","category2"),
    sep = "!!"
  )

dec_vars_2010 %>% 
  filter(grepl("P1",name)) %>% 
  select(name, label) %>% 
  arrange(name)

smc_pop_race_2010 <- smc_pop_race_2010 %>% 
  mutate(
    race = case_when(
      category1 == "Population of two or more races:" & is.na(category2) ~ "Two or more races",
      category1 == "Population of two or more races:" ~ "",
      !is.na(category2) ~ category2,
      TRUE ~ ""
    )
  )

smc_pop_race_2010 <- smc_pop_race_2010 %>% 
  filter(race != "") %>% 
  select(block, race, pop = estimate
  )

blocks_2010 <- blocks("CA", "San Mateo", year = 2010, progress_bar = F)

nfo_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

nfo_pop_2010 <- smc_pop_2010 %>% 
  left_join(blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf() %>% 
  st_centroid() %>% 
  .[nfo_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(blocks_2010 %>% select(block = GEOID10)) %>% 
  st_as_sf()
```

```{r}
place_boundary <- places("CA", progress_bar = F) %>% 
  filter(NAME == "North Fair Oaks")

colnames(nfo_pop_2010)<- c("GEOID10","pop","geometry")
  
place_blocks_2010 <-
  blocks_2010 %>% 
  st_centroid() %>% 
  .[place_boundary, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(blocks_2010 %>% select(GEOID10)) %>% 
  st_as_sf()
  
mapview(place_boundary) + mapview(place_blocks_2010, alpha.regions = 0, color = "red", lwd = 2)
```

```{r}
#Now, I will use spatial subsetting from 2.4 to see where 2020 North Fair Oaks blocks intersect with 2010 North Fair Oaks blocks
place_blocks_2020 <- blocks_2020 %>%
  st_centroid() %>%
  .[place_boundary, ] %>% 
  st_set_geometry(NULL) %>%
  left_join(blocks_2020 %>% select(GEOID20)) %>%
  st_as_sf()
```

```{r}
#This is where I ran into issues with this assignment. I know that I need to have a pop_2020 variable, but I have no pop column and cannot figure out how to left_join in order to add this column because column names aren't lining up. I was trying to left_join nfo_pop_2010 with the block dataframe. I have commented out the sections that are not running correctly here.
#place_blocks_2020_intersect <- place_blocks_2020 %>% 
  #st_transform(26910) %>% 
  #mutate(original_area = st_area(.)) %>% 
  #st_intersection(
    #place_boundary %>% 
    #select(block = GEOID20) %>%
      #st_transform(26910)
  #) %>% 
  #mutate(
    #leftover_area = st_area(.),
    #perc_area = as.numeric(leftover_area / original_area),
    #pop_2020 = pop * perc_area
  #)

#Now, if my previous code had worked, I would reshape the 2020 blocks based on where the 2010 and 2020 blocks intersect. I have once again commented out pop_2020
#place_blocks_2020_reshaped <- place_blocks_2020_intersect %>%
  #st_drop_geometry() %>% 
  #group_by(block) %>% 
  #summarize(
    #pop_2020 = sum(___, na.rm=T) %>% round()
  #)

# Now, if my previous code had worked, I would compute the absolute population difference between 2020 and 2010. I also would translate absolute difference in population to population per acre. 
#projection <-
#place_pop_2010_2020 <- place_blocks_2010
  #left_join(as.data.frame(place_blocks_2010))%>% 
  #mutate(
    #absolute_pop= (place_blocks_2020 - place_blocks_2010) / as.numeric(perc_area) * 43560
  #)

#absolute_pal <- colorNumeric(
  #palette = "Reds",
  #domain = 
      #place_pop_2010_2020$absolute_pop
#)

#Finally, I would create a map with the above data.
#leaflet() %>% 
  #addProviderTiles(provider = providers$CartoDB.Positron) %>% 
  #addPolygons(
    #fillColor = ~absolute_pal(absolute_pop),
    #label = ~round(absolute_pop),
    #color = "white",
    #opacity = 0.5,
    #fillOpacity = 0.75,
    #weight = 1,
  #) %>% 
  #addLegend(
    #pal = absolute_pal,
    #values = ~absolute_pop,
    #title = "Absolute Change in Population, North Fair Oaks (2010-2020)"
  #) 
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
